# Generated by Django 4.1.3 on 2022-11-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_username_company_name_company_description_and_more'),
        ('faculty', '0002_rename_pco_pcoadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stunum', models.IntegerField()),
                ('batch', models.DateField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.company')),
            ],
        ),
    ]
