# Generated by Django 4.1.3 on 2022-11-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='HRname',
            new_name='username',
        ),
    ]
