# Generated by Django 4.1.3 on 2022-11-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcon',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
